version: "2"

networks:
  default:
    external:
      name: main

services:
  volvo-api:
    build: .
    container_name: web.volvo-api
    environment:
      - NODE_ENV=development
      - VIRTUAL_HOST=volvo-api.albertokato.com.br
      - VIRTUAL_PORT=3000
    expose:
      - "3000"
    external_links:
      - nginx-proxy.web-base
    volumes:
      - .:/application
      - .:/mnt/base
      - /application/node_modules
    working_dir: /application
    entrypoint: npm
    command: run production
